### ISSUE TITLE
Add page to view jobs

### ISSUE THREAD

**Issue by jonblack** [cmbi/xssp-api#10]
It should be possible to view the jobs running and waiting in the queue via a web interface.

**Comment by touwwouter** [comment]
@jonblack would this be easy to copy from hope-flask?

**Comment by jonblack** [comment]
No, this is a lot of work. Celery/rabbitmq only track temporary information. hope-flask saves jobs to a mongodb database so the status can be looked up later on.

**Comment by cbaakman** [comment]
MRS works with job files in a cache dir. This way, the web frontend knows which job ids exist.
We could do that with the xssp frontend also.

**Comment by jonblack** [comment]
We've has some issues with the job files in the cache dir and that approach doesn't offer any benefits over using a mongo database. I suppose using the same approach as in HOPE is a reasonable idea. Shall we give it a go and see where it leads us?

**Comment by cbaakman** [comment]
Currently, the branch at https://github.com/cbaakman/xssp-rest/tree/mongo-storage-jobs shows the list of jobs. (failed, running, finished, etc.) The list can be infinitely long, so we should discuss what happens if the list exceeds a certain number.

Should there also be an option to remove jobs. That would require credentials right?

**Comment by jonblack** [comment]
I wouldn't worry about removing jobs, lets just list the status for now. As for the list growing large, HOPE paginates the results. We could do the same here.
