### ISSUE TITLE
HSSP doesn't contain all PDB chains

### ISSUE THREAD

**Issue by crimcc** [cmbi/xssp-api#100]
Dear XSSP team, 

First of all thank you very much for the service, and I really like this service and very helpful.

I found that HSSP sometimes doesn't process all chains in PDB.
For example, PDB ID 2JEV only processes chain A, but there exists two chains as shown below. 
SEQLENGTH   169
NCHAIN        2 chain(s) in 2JEV data set
KCHAIN        1 chain(s) used here ; chains(s) : A
NALIGN      225

I need to get all chains in "## SEQUENCE PROFILE AND ENTROPY" section from HSSP output.
So far, I have found 871 PDB IDs that HSSP doesn't process full PDB chains.

Could you tell me why it happens? 
I will appreciate if you can help me to get full chains of these 871 PDBs. 

Sincerely, 

JC

**Comment by cbaakman** [comment]
Dear user,

the reason why only chain A is shown in this example is because chain B is considered the same as chain A. This decision was made by comparing the sequences of the two chains. These sequences are based on ATOM records in the PDB file. NOT the seqres records.

Since both chains have the same sequence, their sequence profile and entropy will also look the same. So you can simply duplicate it.

**Comment by crimcc** [comment]
Thank you for the prompt reply.
