### ISSUE TITLE
Website Broken

### ISSUE THREAD

**Issue by 1000000000000000000000000000000** [cmbi/xssp-api#105]
After successfully using this great website and API for months, I am having difficulties now. See error here:

![image](https://user-images.githubusercontent.com/81730040/150599684-51141fbb-3cca-4d45-967e-d4865bbacb84.png)

What changed? Can someone please fix this?

**Comment by cbaakman** [comment]
Dear User,


thanks for bringing this to our attention. It seems mkdssp wasn't accessible.


It's fixed now.

________________________________
Van: 1000000000000000000000000000000 ***@***.***>
Verzonden: vrijdag 21 januari 2022 22:03:05
Aan: cmbi/xssp-api
CC: Subscribed
Onderwerp: [cmbi/xssp-api] Website Broken (Issue #105)


After successfully using this great website and API for months, I am having difficulties now. See error here:

[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F81730040%2F150599684-51141fbb-3cca-4d45-967e-d4865bbacb84.png&data=04%7C01%7CCoos.Baakman%40radboudumc.nl%7Cb3bcfc43de3f4a858e1608d9dd216c5b%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637783957893343687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=txbIgyrU5jYPbmytJ5l1qiGPXONlQQDsjr%2F549Pbiws%3D&reserved=0>

What changed? Can someone please fix this?

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcmbi%2Fxssp-api%2Fissues%2F105&data=04%7C01%7CCoos.Baakman%40radboudumc.nl%7Cb3bcfc43de3f4a858e1608d9dd216c5b%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637783957893343687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BS%2Fz57gyx8YtT9fso8hYpmNKyUk5pyN2eaKa8ESjEb0%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABJXLMZWJFCQMUN2IVTLHTDUXHCYTANCNFSM5MQRLFPQ&data=04%7C01%7CCoos.Baakman%40radboudumc.nl%7Cb3bcfc43de3f4a858e1608d9dd216c5b%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637783957893343687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5HVIJ26RU95FpGxOLTOPLMjwqCtjpTVNvoKLaGu5E7g%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CCoos.Baakman%40radboudumc.nl%7Cb3bcfc43de3f4a858e1608d9dd216c5b%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637783957893343687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IqHCHciymmprqdXWb0QpLU4CTuTjBuKR9WMaUSvCvwU%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CCoos.Baakman%40radboudumc.nl%7Cb3bcfc43de3f4a858e1608d9dd216c5b%7Cb208fe69471e48c48d87025e9b9a157f%7C1%7C0%7C637783957893343687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WOY1Nvmank1gOmguY9QitZ1HKZHDDcOKXfZK1UdSIBY%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

De informatie in dit bericht is uitsluitend bestemd voor de geadresseerde. Aan dit bericht en de bijlagen kunnen geen rechten worden ontleend. Heeft u deze e-mail onbedoeld ontvangen? Dan verzoeken wij u het te vernietigen en de afzender te informeren. Openbaar maken, kopiëren en verspreiden van deze e-mail of informatie uit deze e-mail is alleen toegestaan met voorafgaande schriftelijke toestemming van de afzender. Het Radboudumc staat geregistreerd bij de Kamer van Koophandel in het handelsregister onder nummer 80262783.

The content of this message is intended solely for the addressee. No rights can be derived from this message or its attachments. If you are not the intended recipient, we kindly request you to delete the message and inform the sender. It is strictly prohibited to disclose, copy or distribute this email or the information inside it, without a written consent from the sender. Radboud university medical center is registered with the Dutch Chamber of Commerce trade register with number 80262783.

**Comment by 1000000000000000000000000000000** [comment]
The website might be broken again. Well this time it seems to be a style issue.

The website looks like this currently:
![image](https://user-images.githubusercontent.com/81730040/190285895-ebdf563e-242e-4998-925f-1b581faef0b6.png)

**Comment by cbaakman** [comment]
The system administrator fixed the nginx configuration of the proxy. Right now, the website works again.
